apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: routes.serving.knative.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.domain
    name: Domain
    type: string
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=='Ready')].reason
    name: Reason
    type: string
  group: serving.knative.dev
  names:
    categories:
    - all
    - knative
    - serving
    kind: Route
    plural: routes
    shortNames:
    - rt
    singular: route
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec holds the desired state of the Route (from the client).
          properties:
            generation:
              description: 'DeprecatedGeneration was used prior in Kubernetes versions
                <1.11 when metadata.generation was not being incremented by the api
                server  This property will be dropped in future Knative releases and
                should not be used - use metadata.generation  Tracking issue: https://github.com/knative/serving/issues/643'
              format: int64
              type: integer
            traffic:
              description: Traffic specifies how to distribute traffic over a collection
                of Knative Serving Revisions and Configurations.
              items:
                properties:
                  configurationName:
                    description: ConfigurationName of a configuration to whose latest
                      revision we will send this portion of traffic. When the "status.latestReadyRevisionName"
                      of the referenced configuration changes, we will automatically
                      migrate traffic from the prior "latest ready" revision to the
                      new one. This field is never set in Route's status, only its
                      spec. This is mutually exclusive with RevisionName.
                    type: string
                  name:
                    description: 'Name is optionally used to expose a dedicated hostname
                      for referencing this target exclusively. It has the form: {name}.${route.status.domain}'
                    type: string
                  percent:
                    description: Percent specifies percent of the traffic to this
                      Revision or Configuration. This defaults to zero if unspecified.
                    format: int64
                    type: integer
                  revisionName:
                    description: RevisionName of a specific revision to which to send
                      this portion of traffic. This is mutually exclusive with ConfigurationName.
                    type: string
                required:
                - percent
                type: object
              type: array
          type: object
        status:
          description: Status communicates the observed state of the Route (from the
            controller).
          properties:
            address:
              description: Address holds the information needed for a Route to be
                the target of an event.
              properties:
                hostname:
                  type: string
              type: object
            conditions:
              description: Conditions the latest available observations of a resource's
                current state. +patchMergeKey=type +patchStrategy=merge
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time the condition
                      transitioned from one status to another. We use VolatileTime
                      in place of metav1.Time to exclude this from creating equality.Semantic
                      differences (all other things held constant).
                    type: object
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  severity:
                    description: Severity with which to treat failures of this type
                      of condition. When this is not specified, it defaults to Error.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                      +required
                    type: string
                  type:
                    description: Type of condition. +required
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            domain:
              description: Domain holds the top-level domain that will distribute
                traffic over the provided targets. It generally has the form {route-name}.{route-namespace}.{cluster-level-suffix}
              type: string
            domainInternal:
              description: 'DeprecatedDomainInternal holds the top-level domain that
                will distribute traffic over the provided targets from inside the
                cluster. It generally has the form {route-name}.{route-namespace}.svc.{cluster-domain-name}
                DEPRECATED: Use Address instead.'
              type: string
            observedGeneration:
              description: ObservedGeneration is the 'Generation' of the Service that
                was last processed by the controller.
              format: int64
              type: integer
            traffic:
              description: Traffic holds the configured traffic distribution. These
                entries will always contain RevisionName references. When ConfigurationName
                appears in the spec, this will hold the LatestReadyRevisionName that
                we last observed.
              items:
                properties:
                  configurationName:
                    description: ConfigurationName of a configuration to whose latest
                      revision we will send this portion of traffic. When the "status.latestReadyRevisionName"
                      of the referenced configuration changes, we will automatically
                      migrate traffic from the prior "latest ready" revision to the
                      new one. This field is never set in Route's status, only its
                      spec. This is mutually exclusive with RevisionName.
                    type: string
                  name:
                    description: 'Name is optionally used to expose a dedicated hostname
                      for referencing this target exclusively. It has the form: {name}.${route.status.domain}'
                    type: string
                  percent:
                    description: Percent specifies percent of the traffic to this
                      Revision or Configuration. This defaults to zero if unspecified.
                    format: int64
                    type: integer
                  revisionName:
                    description: RevisionName of a specific revision to which to send
                      this portion of traffic. This is mutually exclusive with ConfigurationName.
                    type: string
                required:
                - percent
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
